language: python
cache: pip
sudo: false
git:
    depth: 3
python:
    - "3.5"
    - "3.6"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install codecov

script: 
    - python manage.py test --coverage

after_success:
    - codecov

