codecov:
    notify:
        require_ci_to_pass: no

comment:
    layout: header, changes, diff

coverage:
    ignore:
        - tests/*
        - config.py
        - manage.py
        - */__init__.py
        - */site-packages/*
  
