"""empty message

Revision ID: 77b94550f2ea
Revises: 7b6db31373a3
Create Date: 2017-05-24 18:36:54.598607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b94550f2ea'
down_revision = '7b6db31373a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaders',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_index(op.f('ix_leaders_username'), 'leaders', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('authorised', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_leaders_username'), table_name='leaders')
    op.drop_table('leaders')
    # ### end Alembic commands ###
