"""empty message

Revision ID: 7b6db31373a3
Revises: 
Create Date: 2017-04-25 13:12:54.741194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6db31373a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_codes_code_id'), 'codes', ['code_id'], unique=False)
    op.create_table('project_codes',
    sa.Column('project_code_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_code_id')
    )
    op.create_index(op.f('ix_project_codes_project_code_id'), 'project_codes', ['project_code_id'], unique=False)
    op.create_table('raw',
    sa.Column('respondent_id', sa.BigInteger(), nullable=False),
    sa.Column('collector_id', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_url', sa.String(), nullable=True),
    sa.Column('cat_work_or_personal', sa.String(length=20), nullable=True),
    sa.Column('comment_what_work', sa.String(), nullable=True),
    sa.Column('comment_why_you_came', sa.String(), nullable=True),
    sa.Column('cat_found_looking_for', sa.String(length=20), nullable=True),
    sa.Column('comment_other_found_what', sa.String(), nullable=True),
    sa.Column('cat_satisfaction', sa.String(length=50), nullable=True),
    sa.Column('comment_other_where_for_help', sa.String(), nullable=True),
    sa.Column('cat_anywhere_else_help', sa.String(length=30), nullable=True),
    sa.Column('comment_other_else_help', sa.String(), nullable=True),
    sa.Column('comment_where_for_help', sa.String(), nullable=True),
    sa.Column('comment_further_comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('respondent_id')
    )
    op.create_index(op.f('ix_raw_end_date'), 'raw', ['end_date'], unique=False)
    op.create_index(op.f('ix_raw_respondent_id'), 'raw', ['respondent_id'], unique=False)
    op.create_index(op.f('ix_raw_start_date'), 'raw', ['start_date'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('urls',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('full_url', sa.String(), nullable=True),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('section0', sa.String(), nullable=True),
    sa.Column('section1', sa.String(), nullable=True),
    sa.Column('section2', sa.String(), nullable=True),
    sa.Column('section3', sa.String(), nullable=True),
    sa.Column('org0', sa.String(), nullable=True),
    sa.Column('org1', sa.String(), nullable=True),
    sa.Column('org2', sa.String(), nullable=True),
    sa.Column('org3', sa.String(), nullable=True),
    sa.Column('org4', sa.String(), nullable=True),
    sa.Column('lookup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('url_id')
    )
    op.create_index(op.f('ix_urls_full_url'), 'urls', ['full_url'], unique=False)
    op.create_index(op.f('ix_urls_lookup_date'), 'urls', ['lookup_date'], unique=False)
    op.create_index(op.f('ix_urls_org0'), 'urls', ['org0'], unique=False)
    op.create_index(op.f('ix_urls_org1'), 'urls', ['org1'], unique=False)
    op.create_index(op.f('ix_urls_org2'), 'urls', ['org2'], unique=False)
    op.create_index(op.f('ix_urls_org3'), 'urls', ['org3'], unique=False)
    op.create_index(op.f('ix_urls_org4'), 'urls', ['org4'], unique=False)
    op.create_index(op.f('ix_urls_page'), 'urls', ['page'], unique=False)
    op.create_index(op.f('ix_urls_section0'), 'urls', ['section0'], unique=False)
    op.create_index(op.f('ix_urls_section1'), 'urls', ['section1'], unique=False)
    op.create_index(op.f('ix_urls_section2'), 'urls', ['section2'], unique=False)
    op.create_index(op.f('ix_urls_section3'), 'urls', ['section3'], unique=False)
    op.create_index(op.f('ix_urls_url_id'), 'urls', ['url_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('classified',
    sa.Column('classified_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.BigInteger(), nullable=True),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('project_code_id', sa.Integer(), nullable=True),
    sa.Column('pii', sa.Boolean(), nullable=True),
    sa.Column('date_coded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['coder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code_id'], ['project_codes.project_code_id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['raw.respondent_id'], ),
    sa.PrimaryKeyConstraint('classified_id')
    )
    op.create_index(op.f('ix_classified_classified_id'), 'classified', ['classified_id'], unique=False)
    op.create_index(op.f('ix_classified_code_id'), 'classified', ['code_id'], unique=False)
    op.create_index(op.f('ix_classified_coder_id'), 'classified', ['coder_id'], unique=False)
    op.create_index(op.f('ix_classified_pii'), 'classified', ['pii'], unique=False)
    op.create_index(op.f('ix_classified_project_code_id'), 'classified', ['project_code_id'], unique=False)
    op.create_index(op.f('ix_classified_respondent_id'), 'classified', ['respondent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classified_respondent_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_project_code_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_pii'), table_name='classified')
    op.drop_index(op.f('ix_classified_coder_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_code_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_classified_id'), table_name='classified')
    op.drop_table('classified')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_urls_url_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_section3'), table_name='urls')
    op.drop_index(op.f('ix_urls_section2'), table_name='urls')
    op.drop_index(op.f('ix_urls_section1'), table_name='urls')
    op.drop_index(op.f('ix_urls_section0'), table_name='urls')
    op.drop_index(op.f('ix_urls_page'), table_name='urls')
    op.drop_index(op.f('ix_urls_org4'), table_name='urls')
    op.drop_index(op.f('ix_urls_org3'), table_name='urls')
    op.drop_index(op.f('ix_urls_org2'), table_name='urls')
    op.drop_index(op.f('ix_urls_org1'), table_name='urls')
    op.drop_index(op.f('ix_urls_org0'), table_name='urls')
    op.drop_index(op.f('ix_urls_lookup_date'), table_name='urls')
    op.drop_index(op.f('ix_urls_full_url'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_raw_start_date'), table_name='raw')
    op.drop_index(op.f('ix_raw_respondent_id'), table_name='raw')
    op.drop_index(op.f('ix_raw_end_date'), table_name='raw')
    op.drop_table('raw')
    op.drop_index(op.f('ix_project_codes_project_code_id'), table_name='project_codes')
    op.drop_table('project_codes')
    op.drop_table('priority')
    op.drop_index(op.f('ix_codes_code_id'), table_name='codes')
    op.drop_table('codes')
    # ### end Alembic commands ###
