"""empty message

Revision ID: 81ea30e07bf6
Revises: 
Create Date: 2017-04-10 16:57:11.985986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ea30e07bf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table('project_codes',
    sa.Column('project_code_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_code_id')
    )
    op.create_table('raw',
    sa.Column('respondent_id', sa.BigInteger(), nullable=False),
    sa.Column('collector_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_url', sa.String(), nullable=True),
    sa.Column('cat_work_or_personal', sa.String(length=20), nullable=True),
    sa.Column('comment_what_work', sa.String(), nullable=True),
    sa.Column('comment_why_you_came', sa.String(), nullable=True),
    sa.Column('cat_found_looking_for', sa.String(length=20), nullable=True),
    sa.Column('comment_other_found_what', sa.String(), nullable=True),
    sa.Column('cat_satisfaction', sa.String(length=50), nullable=True),
    sa.Column('comment_other_where_for_help', sa.String(), nullable=True),
    sa.Column('cat_anywhere_else_help', sa.String(length=30), nullable=True),
    sa.Column('comment_other_else_help', sa.String(), nullable=True),
    sa.Column('comment_where_for_help', sa.String(), nullable=True),
    sa.Column('comment_further_comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('respondent_id')
    )
    op.create_index(op.f('ix_raw_end_date'), 'raw', ['end_date'], unique=False)
    op.create_index(op.f('ix_raw_respondent_id'), 'raw', ['respondent_id'], unique=False)
    op.create_index(op.f('ix_raw_start_date'), 'raw', ['start_date'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('classified',
    sa.Column('classified_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.BigInteger(), nullable=True),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('project_code_id', sa.Integer(), nullable=True),
    sa.Column('pip', sa.Boolean(), nullable=True),
    sa.Column('date_coded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['coder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code_id'], ['project_codes.project_code_id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['raw.respondent_id'], ),
    sa.PrimaryKeyConstraint('classified_id')
    )
    op.create_index(op.f('ix_classified_classified_id'), 'classified', ['classified_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classified_classified_id'), table_name='classified')
    op.drop_table('classified')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_raw_start_date'), table_name='raw')
    op.drop_index(op.f('ix_raw_respondent_id'), table_name='raw')
    op.drop_index(op.f('ix_raw_end_date'), table_name='raw')
    op.drop_table('raw')
    op.drop_table('project_codes')
    op.drop_table('codes')
    # ### end Alembic commands ###
