"""empty message

Revision ID: c6b8a822a928
Revises: 7b6db31373a3
Create Date: 2017-05-02 20:58:29.065050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b8a822a928'
down_revision = '7b6db31373a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority',
    sa.Column('respondent_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=True),
    sa.Column('max', sa.BigInteger(), nullable=True),
    sa.Column('ratio', sa.Numeric(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('coders', sa.ARRAY(Integer()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('respondent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priority')
    # ### end Alembic commands ###
