"""empty message

Revision ID: ebf69c8fce44
Revises: 
Create Date: 2017-04-12 15:49:34.741310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf69c8fce44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_codes_code_id'), 'codes', ['code_id'], unique=False)
    op.create_table('priority',
    sa.Column('respondent_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('max', sa.BigInteger(), nullable=True),
    sa.Column('ratio', sa.Numeric(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('respondent_id')
    )
    op.create_table('project_codes',
    sa.Column('project_code_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_code_id')
    )
    op.create_index(op.f('ix_project_codes_project_code_id'), 'project_codes', ['project_code_id'], unique=False)
    op.create_table('raw',
    sa.Column('respondent_id', sa.BigInteger(), nullable=False),
    sa.Column('collector_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_url', sa.String(), nullable=True),
    sa.Column('cat_work_or_personal', sa.String(length=20), nullable=True),
    sa.Column('comment_what_work', sa.String(), nullable=True),
    sa.Column('comment_why_you_came', sa.String(), nullable=True),
    sa.Column('cat_found_looking_for', sa.String(length=20), nullable=True),
    sa.Column('comment_other_found_what', sa.String(), nullable=True),
    sa.Column('cat_satisfaction', sa.String(length=50), nullable=True),
    sa.Column('comment_other_where_for_help', sa.String(), nullable=True),
    sa.Column('cat_anywhere_else_help', sa.String(length=30), nullable=True),
    sa.Column('comment_other_else_help', sa.String(), nullable=True),
    sa.Column('comment_where_for_help', sa.String(), nullable=True),
    sa.Column('comment_further_comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('respondent_id')
    )
    op.create_index(op.f('ix_raw_end_date'), 'raw', ['end_date'], unique=False)
    op.create_index(op.f('ix_raw_respondent_id'), 'raw', ['respondent_id'], unique=False)
    op.create_index(op.f('ix_raw_start_date'), 'raw', ['start_date'], unique=False)
    op.create_table('classified',
    sa.Column('classified_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.BigInteger(), nullable=True),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('project_code_id', sa.Integer(), nullable=True),
    sa.Column('pip', sa.Boolean(), nullable=True),
    sa.Column('date_coded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['coder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code_id'], ['project_codes.project_code_id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['raw.respondent_id'], ),
    sa.PrimaryKeyConstraint('classified_id')
    )
    op.create_index(op.f('ix_classified_classified_id'), 'classified', ['classified_id'], unique=False)
    op.create_index(op.f('ix_classified_code_id'), 'classified', ['code_id'], unique=False)
    op.create_index(op.f('ix_classified_coder_id'), 'classified', ['coder_id'], unique=False)
    op.create_index(op.f('ix_classified_pip'), 'classified', ['pip'], unique=False)
    op.create_index(op.f('ix_classified_project_code_id'), 'classified', ['project_code_id'], unique=False)
    op.create_index(op.f('ix_classified_respondent_id'), 'classified', ['respondent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classified_respondent_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_project_code_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_pip'), table_name='classified')
    op.drop_index(op.f('ix_classified_coder_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_code_id'), table_name='classified')
    op.drop_index(op.f('ix_classified_classified_id'), table_name='classified')
    op.drop_table('classified')
    op.drop_index(op.f('ix_raw_start_date'), table_name='raw')
    op.drop_index(op.f('ix_raw_respondent_id'), table_name='raw')
    op.drop_index(op.f('ix_raw_end_date'), table_name='raw')
    op.drop_table('raw')
    op.drop_index(op.f('ix_project_codes_project_code_id'), table_name='project_codes')
    op.drop_table('project_codes')
    op.drop_table('priority')
    op.drop_index(op.f('ix_codes_code_id'), table_name='codes')
    op.drop_table('codes')
    # ### end Alembic commands ###
